# Site settings
title: Lance Barlaan's blog
email: lptbarlaan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Likes building stuff from top to bottom, interested in how people learn, build and think about everything in between.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: lanceptb
github_username:  lanceptb
linkedin_username: lanceptb
# Build settings
markdown: kramdown
